services:
  app:
    build: .
    container_name: laravel_cm_demo_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: postgres_cm_demo
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_mc_demo_cache

volumes:
  pgdata:
